---
site: bookdown::bookdown_site
output:
  bookdown::pdf_document2:
    fig_caption: yes
    toc: yes
    latex_engine: xelatex
header-includes:
   - \usepackage{floatrow}
   - \floatsetup[figure]{capposition=top}
classoption: landscape
---
## Bristol

```{r ModelBristolPaths, include=FALSE}
path = "/Users/travel_mechtal/Documents/UWE/Portfolio/"
```

```{r ModelBristolLibraries, include=FALSE}
#---------------------------------------
# Plotting
#---------------------------------------
if(!require(ggplot2)){install.packages("ggplot2")}
library(ggplot2)
#---------------------------------------
# Working with objects
#---------------------------------------
if(!require(dplyr)){install.packages("dplyr")}
library(dplyr) #rename
#---------------------------------------
# Knitting to pdf
#---------------------------------------
if(!require(knitr)){install.packages("knitr")}
library(knitr)
```

```{r ModelBristolDataset, include=FALSE}
# read the data
dataset <- read.csv(paste0(path,"ltla_2022-03-25.csv"),
                         header = TRUE,
                         sep = ","
                         )

# change date's format
dataset$date <- as.Date(dataset$date,format = '%Y-%m-%d')
# rename columns
dataset = rename(dataset, 
       First = newPeopleVaccinatedFirstDoseByVaccinationDate
       ,Second = newPeopleVaccinatedSecondDoseByVaccinationDate
       ,Third = newPeopleVaccinatedThirdInjectionByVaccinationDate
         )
# choose columns
dataset <- dataset[c("age", "date", "First", "Second", "Third")]
```

Add the column "Age" for the model using Ordinal Encoding and look at the dataset.

```{r ModelBristolDatasetHead, echo=FALSE}
age_ord <- unique(dataset["age"])
dataset$Age <- which(age_ord == dataset$age)
kable(head(dataset))
```

I am going to use the k-means clustering model.

```{r ModelBristolFirst, include=FALSE}
y_column = "First"
```

```{r ModelBristolKmeans, echo=FALSE}
# k-means clustering model
cls <- kmeans(x = data.matrix(dataset[,c("Age", y_column)]), centers = 5)
dataset$cluster <- as.character(cls$cluster)

# plot
ggplot() +
  geom_point(data = dataset, 
             mapping = aes_string(x = "age", 
                                  y = y_column, 
                                  colour = "cluster")) +
theme(axis.text.x = element_text(angle=90, hjust = 1))
```

```{r ModelBristolSecond, echo=FALSE}
y_column = "Second"
<<ModelBristolKmeans>>
```

```{r ModelBristolThird, echo=FALSE}
y_column = "Third"
<<ModelBristolKmeans>>
```

As we can see, sometimes a lot of people in the same age group got their jabs together. This fact may be useful for modeling.